//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.8.0.0
//     Timestamp      : 13/09/2021 16:21:58
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE XanthiClientTest

    PUBLIC PARTIAL CLASS ServerManager
        PRIVATE components := NULL AS System.ComponentModel.IContainer
        PRIVATE label1 AS System.Windows.Forms.Label
        PRIVATE buttonStop AS System.Windows.Forms.Button
        PRIVATE serverIP AS System.Windows.Forms.Label
        PRIVATE listBoxClients AS System.Windows.Forms.ListBox

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .and. (components != null))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
   RETURN

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        PRIVATE METHOD InitializeComponent() AS VOID STRICT
            SELF:listBoxClients := System.Windows.Forms.ListBox{}
            SELF:label1 := System.Windows.Forms.Label{}
            SELF:buttonStop := System.Windows.Forms.Button{}
            SELF:serverIP := System.Windows.Forms.Label{}
            SELF:SuspendLayout()
            // 
            // listBoxClients
            // 
            SELF:listBoxClients:FormattingEnabled := true
            SELF:listBoxClients:ItemHeight := 16
            SELF:listBoxClients:Location := System.Drawing.Point{12, 56}
            SELF:listBoxClients:Name := "listBoxClients"
            SELF:listBoxClients:Size := System.Drawing.Size{279, 212}
            SELF:listBoxClients:TabIndex := 0
            // 
            // label1
            // 
            SELF:label1:AutoSize := true
            SELF:label1:Location := System.Drawing.Point{12, 9}
            SELF:label1:Name := "label1"
            SELF:label1:Size := System.Drawing.Size{58, 17}
            SELF:label1:TabIndex := 1
            SELF:label1:Text := "Server :"
            // 
            // buttonStop
            // 
            SELF:buttonStop:Location := System.Drawing.Point{216, 6}
            SELF:buttonStop:Name := "buttonStop"
            SELF:buttonStop:Size := System.Drawing.Size{75, 28}
            SELF:buttonStop:TabIndex := 2
            SELF:buttonStop:Text := "Stop"
            SELF:buttonStop:UseVisualStyleBackColor := true
            SELF:buttonStop:Click += System.EventHandler{ SELF, @buttonStop_Click() }
            // 
            // serverIP
            // 
            SELF:serverIP:AutoSize := true
            SELF:serverIP:Location := System.Drawing.Point{76, 9}
            SELF:serverIP:Name := "serverIP"
            SELF:serverIP:Size := System.Drawing.Size{128, 17}
            SELF:serverIP:TabIndex := 3
            SELF:serverIP:Text := "XXX.XXX.XXX.XXX"
            // 
            // ServerManager
            // 
            SELF:AutoScaleDimensions := System.Drawing.SizeF{8, 16}
            SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            SELF:ClientSize := System.Drawing.Size{314, 287}
            SELF:Controls:Add(SELF:serverIP)
            SELF:Controls:Add(SELF:buttonStop)
            SELF:Controls:Add(SELF:label1)
            SELF:Controls:Add(SELF:listBoxClients)
            SELF:MaximizeBox := false
            SELF:MinimizeBox := false
            SELF:Name := "ServerManager"
            SELF:Text := "Server Manager"
            SELF:FormClosing += System.Windows.Forms.FormClosingEventHandler{ SELF, @ServerManager_FormClosing() }
            SELF:Load += System.EventHandler{ SELF, @ServerManager_Load() }
            SELF:ResumeLayout(false)
            SELF:PerformLayout()

        #endregion
    END CLASS 
END NAMESPACE
